/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as RepresentationImport } from './routes/representation'
import { Route as IndexImport } from './routes/index'
import { Route as QuestIndexImport } from './routes/quest/index'
import { Route as QuestIdImport } from './routes/quest/$id'
import { Route as Q85432Import } from './routes/q/85432'
import { Route as Q78943Import } from './routes/q/78943'

// Create/Update Routes

const RepresentationRoute = RepresentationImport.update({
  path: '/representation',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const QuestIndexRoute = QuestIndexImport.update({
  path: '/quest/',
  getParentRoute: () => rootRoute,
} as any)

const QuestIdRoute = QuestIdImport.update({
  path: '/quest/$id',
  getParentRoute: () => rootRoute,
} as any)

const Q85432Route = Q85432Import.update({
  path: '/q/85432',
  getParentRoute: () => rootRoute,
} as any)

const Q78943Route = Q78943Import.update({
  path: '/q/78943',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/representation': {
      id: '/representation'
      path: '/representation'
      fullPath: '/representation'
      preLoaderRoute: typeof RepresentationImport
      parentRoute: typeof rootRoute
    }
    '/q/78943': {
      id: '/q/78943'
      path: '/q/78943'
      fullPath: '/q/78943'
      preLoaderRoute: typeof Q78943Import
      parentRoute: typeof rootRoute
    }
    '/q/85432': {
      id: '/q/85432'
      path: '/q/85432'
      fullPath: '/q/85432'
      preLoaderRoute: typeof Q85432Import
      parentRoute: typeof rootRoute
    }
    '/quest/$id': {
      id: '/quest/$id'
      path: '/quest/$id'
      fullPath: '/quest/$id'
      preLoaderRoute: typeof QuestIdImport
      parentRoute: typeof rootRoute
    }
    '/quest/': {
      id: '/quest/'
      path: '/quest'
      fullPath: '/quest'
      preLoaderRoute: typeof QuestIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  RepresentationRoute,
  Q78943Route,
  Q85432Route,
  QuestIdRoute,
  QuestIndexRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/representation",
        "/q/78943",
        "/q/85432",
        "/quest/$id",
        "/quest/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/representation": {
      "filePath": "representation.tsx"
    },
    "/q/78943": {
      "filePath": "q/78943.tsx"
    },
    "/q/85432": {
      "filePath": "q/85432.tsx"
    },
    "/quest/$id": {
      "filePath": "quest/$id.tsx"
    },
    "/quest/": {
      "filePath": "quest/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
