/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as RepresentationImport } from './routes/representation'
import { Route as QuestImport } from './routes/quest'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const RepresentationRoute = RepresentationImport.update({
  path: '/representation',
  getParentRoute: () => rootRoute,
} as any)

const QuestRoute = QuestImport.update({
  path: '/quest',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/quest': {
      id: '/quest'
      path: '/quest'
      fullPath: '/quest'
      preLoaderRoute: typeof QuestImport
      parentRoute: typeof rootRoute
    }
    '/representation': {
      id: '/representation'
      path: '/representation'
      fullPath: '/representation'
      preLoaderRoute: typeof RepresentationImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  QuestRoute,
  RepresentationRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/quest",
        "/representation"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/quest": {
      "filePath": "quest.tsx"
    },
    "/representation": {
      "filePath": "representation.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
